MvcProjeKamp/Controllers/ContentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKamp.Controllers
{
    
    public class ContentController : Controller
    {
        ContentManager contentManager = new ContentManager(new EfContentDal());
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetAllContent(string p)
        {
            p = "";
            var values = contentManager.GetContentList(p);
            
            

            return View(values.ToList());
        }
        public ActionResult ContentByHeading(int id)
        {
            var contentvalues = contentManager.GetListByHeadingID(id);
            return View(contentvalues);
        }
    }
}

MvcProjeKamp/Views/Content/ContentByHeading.cshtml
@using EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "ContentByHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-md-12">
                        <div class="timeline">
                            @foreach (var item in Model)
                            {                            
                            <div class="time-label">
                                <span class="bg-success">@(((DateTime)item.ContentDate).ToString("dd/MMM/yyyy"))</span>
                            </div>
                            <div>
                                <i class="fas fa-comment bg-yellow"></i>
                                <div class="timeline-item">
                                    <h3 class="timeline-header"><a href="#">@item.Writer.WriterName @item.Writer.WriterSurname</a> </h3>
                                    <div class="timeline-body">
                                        @item.ContentText
                                    </div>
                                </div>
                            </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</body>
</html>

MvcProjeKamp/Views/Content/GetAllContent.cshtml
@using EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "GetAllContent";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("GetAllContent", "Content", FormMethod.Post))
{
    <p>
        Aranacak Kelimeyi Giriniz : @Html.TextBox("p")
        <input type="submit" value="Ara" />
    </p>
}
@foreach (var item in Model)
{
    <p>@item.ContentText</p>
}

MvcProjeKamp/Views/Content/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>