MvcProjeKamp/Controllers/WriterPanelContentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKamp.Controllers
{
    public class WriterPanelContentController : Controller
    {
        ContentManager contentManager = new ContentManager(new EfContentDal());
        Context context = new Context();

        public ActionResult MyContent(string p)
        {
            p = (string)Session["WriterMail"];    
            var writeridinfo = context.Writers.Where(x => x.WriterMail == p).Select(y => y.WriterID).FirstOrDefault();
            var contentvalues = contentManager.GetListByWriter(writeridinfo);
            return View(contentvalues);
        }
        [HttpGet]
        public ActionResult AddContent(int id)
        {
            ViewBag.d = id;
            return View();
        }
        [HttpPost]
        public ActionResult AddContent(Content content)
        {
            string mail = (string)Session["WriterMail"];
            var writeridinfo = context.Writers.Where(x => x.WriterMail == mail).Select(y => y.WriterID).FirstOrDefault();
            content.ContentDate = DateTime.Now;
            content.WriterID = writeridinfo;
            content.ContentStatus = true;
            contentManager.ContentAdd(content);
            return RedirectToAction("MyContent");
        }
        public ActionResult ToDoList()
        {
            return View();
        }
    }
}

MvcProjeKamp/Views/WriterPanelContent/AddContent.cshtml
@model EntityLayer.Concrete.Content

@{
    ViewBag.Title = "AddContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>Başlığa İçerik Girişi</h2>
<br />
@using (Html.BeginForm("AddContent", "WriterPanelContent", FormMethod.Post))

{
    <div class="form-group">
        <input type="hidden" name="HeadingID" value="@ViewBag.d"/>
        @Html.Label("İçeriğinizi Yazın")
        @Html.TextAreaFor(x => x.ContentText,4,30, new { @class = "form-control" })
        <br />
        <button class="btn btn-info">Kaydet</button>
    </div>
}

MvcProjeKamp/Views/WriterPanelContent/MyContent.cshtml
@using EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "MyContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}


<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-md-12">
                        <div class="timeline">
                            @foreach (var item in Model)
                            {
                                <div class="time-label">
                                    <span class="bg-success">@(((DateTime)item.ContentDate).ToString("dd/MMM/yyyy"))</span>
                                </div>
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Heading.HeadingName</a> </h3>
                                        <div class="timeline-body">
                                            @item.ContentText
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</body>
</html>

MvcProjeKamp/Views/WriterPanelContent/ToDoList.cshtml
@{
    ViewBag.Title = "ToDoList";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<p>#1 Profilim</p>
<p>#1 Tüm Başlıklarda Paging</p>
<p>#1 Mesajlarda Session</p>
<p>#1 Oturum Yönetiminin Mimariye Taşınması</p>
<p>#5 Token Kullanımı</p>